language: node_js
node_js:
  - '13.11.0'
services: mongodb
deploy:
  provider: lambda
  function_name: "app"
  region: "us-east-1"
  role: "arn:aws:iam::833368887726:role/lambda_deployer"
  runtime: "nodejs12.x"
  handler_name: "handler"